# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color : \"#262626\";\n"
"border : 0.5px solid white;\n"
"border-radius : 7px;\n"
"color : white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.list = QtWidgets.QListWidget(self.centralwidget)
        self.list.setGeometry(QtCore.QRect(615, 11, 171, 511))
        self.list.setObjectName("list")
        self.picture = QtWidgets.QLabel(self.centralwidget)
        self.picture.setGeometry(QtCore.QRect(40, 10, 551, 511))
        self.picture.setObjectName("picture")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 28))
        self.menubar.setObjectName("menubar")
        self.blur_menu = QtWidgets.QMenu(self.menubar)
        self.blur_menu.setObjectName("blur_menu")
        self.coloring_menu = QtWidgets.QMenu(self.menubar)
        self.coloring_menu.setObjectName("coloring_menu")
        self.other_menu = QtWidgets.QMenu(self.menubar)
        self.other_menu.setObjectName("other_menu")
        self.file_menu = QtWidgets.QMenu(self.menubar)
        self.file_menu.setObjectName("file_menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.gaussian_blur = QtWidgets.QAction(MainWindow)
        self.gaussian_blur.setObjectName("gaussian_blur")
        self.bow_blur = QtWidgets.QAction(MainWindow)
        self.bow_blur.setObjectName("bow_blur")
        self.bw_btn = QtWidgets.QAction(MainWindow)
        self.bw_btn.setObjectName("bw_btn")
        self.save_file = QtWidgets.QAction(MainWindow)
        self.save_file.setObjectName("save_file")
        self.inTheLeft = QtWidgets.QAction(MainWindow)
        self.inTheLeft.setObjectName("inTheLeft")
        self.inTheRight = QtWidgets.QAction(MainWindow)
        self.inTheRight.setObjectName("inTheRight")
        self.open_file = QtWidgets.QAction(MainWindow)
        self.open_file.setObjectName("open_file")
        self.blur_menu.addAction(self.gaussian_blur)
        self.blur_menu.addAction(self.bow_blur)
        self.blur_menu.addSeparator()
        self.blur_menu.addSeparator()
        self.coloring_menu.addAction(self.bw_btn)
        self.other_menu.addAction(self.inTheLeft)
        self.other_menu.addAction(self.inTheRight)
        self.file_menu.addAction(self.save_file)
        self.file_menu.addAction(self.open_file)
        self.menubar.addAction(self.file_menu.menuAction())
        self.menubar.addAction(self.blur_menu.menuAction())
        self.menubar.addAction(self.coloring_menu.menuAction())
        self.menubar.addAction(self.other_menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.picture.setText(_translate("MainWindow", "Picture"))
        self.blur_menu.setTitle(_translate("MainWindow", "Blur"))
        self.coloring_menu.setTitle(_translate("MainWindow", "Coloring"))
        self.other_menu.setTitle(_translate("MainWindow", "Other"))
        self.file_menu.setTitle(_translate("MainWindow", "File"))
        self.gaussian_blur.setText(_translate("MainWindow", "Gaussian Blur"))
        self.bow_blur.setText(_translate("MainWindow", "Bow Blur"))
        self.bw_btn.setText(_translate("MainWindow", "Black&White Effect"))
        self.save_file.setText(_translate("MainWindow", "Save File"))
        self.inTheLeft.setText(_translate("MainWindow", "In The Right"))
        self.inTheRight.setText(_translate("MainWindow", "In The Left"))
        self.open_file.setText(_translate("MainWindow", "Open Folder"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
